Vagrant.configure(2) do |config|
  config.vm.box = "hashicorp/precise64"

  config.vm.provision :shell, :path => "vagrant/scripts/basic.sh"
  config.vm.provision :shell, :path => "vagrant/scripts/hadoop.sh"
end
