Vagrant.configure(2) do |config|
  config.vm.box = "hashicorp/precise64"

  config.vm.provision :shell, :path => "vagrant/scripts/basic.sh"

  config.vm.define :gangliamain do |gangliamain|
    gangliamain.vm.network :private_network, ip: "10.10.10.110"
    gangliamain.vm.hostname = "main.foo.com"
    gangliamain.vm.provision :shell, :path => "vagrant/scripts/gangliamain.sh"
  end

  config.vm.define :node1 do |node1|
    node1.vm.network :private_network, ip: "10.10.10.120"
    node1.vm.hostname = "node1.foo.com"
    node1.vm.provision :shell, :path => "vagrant/scripts/ganglia.sh"
  end

  config.vm.define :node2 do |node2|
    node2.vm.network :private_network, ip: "10.10.10.130"
    node2.vm.hostname = "node2.foo.com"
    node2.vm.provision :shell, :path => "vagrant/scripts/ganglia.sh"
  end

end
